#!/usr/bin/env bash

mode='false'
for a
do
  case "$a" in
    console)
      mode='true'
      ;;
    qtconsole)
      mode='true'
      ;;
    notebook)
      mode='true'
      ;;
  esac
done

if [ "$mode" == 'true' ]
then
  ipython3 $@ --profile=julia
else
  ipython3 console $@ --profile=julia
fi
