" PLUGINS {{{1

call plug#begin('~/.nvim/plugged')

" JULIA.VIM {{{2

Plug 'JuliaLang/julia-vim'

" }}}2 END JULIA
" RUST.VIM {{{2

Plug 'wting/rust.vim'

" fold braced blocks
let g:rust_fold = 1

" }}}2 END RUST
" PYTHON-MODE {{{2

Plug 'klen/python-mode'

" USE PYTHON3 YOU WHORES!
"let g:python_host_prog = 'python3'
"let g:pymode_python = 'python3'

" TODO: see if this can be done with python-mode options
set foldlevelstart=99

let g:pymode_rope = 0
let g:pymode_lint_checkers = ['pep8', 'pep257', 'pylint', 'pyflakes']
let g:pymode_syntax_print_as_function = 1
let g:pymode_options_colorcolumn = 0

" }}}2 END PYTHON-MODE
" INCSEARCH.VIM {{{2

Plug 'haya14busa/incsearch.vim'

" incrementally search whole page
map / <Plug>(incsearch-forward)
map ? <Plug>(incsearch-backward)
map g/ <Plug>(incsearch-stay)

" turn off highlighting when non-search related key is pressed
let g:incsearch#auto_nohlsearch = 1
map n <Plug>(incsearch-nohl-n)
map N <Plug>(incsearch-nohl-N)
map * <Plug>(incsearch-nohl-*)
map # <Plug>(incsearch-nohl-#)
map g* <Plug>(incsearch-nohl-g*)
map g# <Plug>(incsearch-nohl-g#)

" n always forward and N always backward
let g:incsearch#consistent_n_direction = 1

" automatically set magic with no portability problems
let g:incsearch#magic = '\v'

" }}}2 END INCSEARCH.VIM
" REPMO.VIM {{{2

Plug 'vim-scripts/repmo.vim'

" }}}2 END REPMO
" CSV.VIM {{{2

Plug 'chrisbra/csv.vim'

" }}}2 END CSV
" COLORSCHEMES {{{2

Plug 'flazz/vim-colorschemes'

" }}}2 END COLORSCHEMES

call plug#end()

" }}}1 END PLUGINS
" GENERAL {{{1

filetype plugin indent on
syntax enable

colorscheme solarized

set encoding=utf-8
set spelllang=en_gb

set noswapfile
set autoread
set autowriteall

set lazyredraw

set clipboard+=unnamed

set history=500

augroup focus
  autocmd!
  autocmd FocusLost * :silent! wall
augroup END

" }}}1 END GENERAL
" MAPPINGS {{{1

let g:mapleader = " "
let g:maplocalleader = "\\"

nnoremap <localleader>e :edit 
nnoremap <Right> <ESC>:bnext<CR>
nnoremap <Left> <ESC>:bprev<CR>

" ' is more convenient than , and has redundancy with `
nnoremap ' ,

" TODO: why doesn't lnoremap work here
inoremap <localleader>jk <ESC>
cnoremap <localleader>jk <ESC>
vnoremap <localleader>jk <ESC>

nnoremap Y y$

noremap <Tab> %

nnoremap <Up> <C-U>
nnoremap <Down> <C-D>

" }}}1 END MAPPINGS
" EDITING {{{1

set nrformats+=alpha

set backspace=indent,eol,start
set whichwrap=h,l
set nojoinspaces
set formatoptions+=j

set shiftround

" incsearch doesn't set magic in substitutions
cnoremap s/ s/\v

set ignorecase
set smartcase
set gdefault

" }}}1 END EDITING
" DISPLAY {{{1

set cursorline

set number
set relativenumber

set ruler
set showcmd

set textwidth=80
set nowrap
" I reckon setting these all to 4 gives the best result nowadays
set tabstop=4  " number of columns <Tab> counts as in normal mode
set shiftwidth=4  " columns added/removed when changing indent level
set softtabstop=4  " amount of whitespace corresponding to tab presses
set expandtab

" }}}1 END DISPLAY

" vim: foldmethod=marker foldlevel=0
