" TODO: Anything (including Fugitive) that comes from a plugin should have an
"     if_has guard around it.
" TODO: Defaults will be changing soon (https://github.com/neovim/neovim/issues/2676)
" NOTE: set viminfo+=! is in plugin/vim-plug-update.vim
" PLUGINS {{{1

let g:plug_window = 'if winwidth(0)/2 < 80 | topleft new | else | vertical topleft new | endif'
command! VimPlugUpgrade silent PlugUpgrade | silent PlugUpdate | quit
if !filereadable($HOME . '/.nvim/autoload/plug.vim')
  silent !curl -fLo ~/.nvim/autoload/plug.vim --create-dirs
        \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * VimPlugUpgrade
endif

call plug#begin('~/.nvim/plugged')

Plug 'benekastah/neomake'
Plug 'ap/vim-buftabline'
Plug 'tpope/vim-fugitive'
Plug 'JuliaLang/julia-vim'
Plug 'rust-lang/rust.vim'
" I want to use this but it's just more trouble than it's worth at the moment.
" It requires system python and a patch to update sys.path before import lldb.
" Maybe when the issues with homebrew's llvm have been sorted I can use it.
" Plug 'critiqjo/lldb.nvim', {'for': 'rust'}
Plug 'klen/python-mode'
Plug 'vim-scripts/matchit.zip'
Plug 'haya14busa/incsearch.vim'
Plug 'vim-scripts/repmo.vim'
Plug 'cespare/vim-toml'
Plug 'chrisbra/csv.vim'
Plug 'flazz/vim-colorschemes'

call plug#end()

" }}}1 END PLUGINS
" GENERAL {{{1

filetype plugin indent on
syntax enable

set foldlevelstart=99

set spelllang=en_gb

set noswapfile
set autoread
set autowriteall

set lazyredraw

set clipboard+=unnamed

set history=500

augroup NeoVimRC
  autocmd!
  autocmd FocusLost * silent wall
  autocmd BufWritePre *
    \ if &ft !=? 'markdown' && expand('%:t') !~ '\v\c^n\?vimrc$' |
    \   silent %s/\s\+$//e |
    \ endif
  autocmd WinEnter term://* startinsert
augroup END

" }}}1 END GENERAL
" MAPPINGS {{{1

let g:mapleader = '\'
let g:maplocalleader = g:mapleader

inoremap <leader>jk <ESC>
vnoremap <leader>jk <ESC>
tnoremap <ESC><ESC> <C-\><C-N>

nnoremap <S-Left> <C-W>h
nnoremap <S-Down> <C-W>j
nnoremap <S-Up> <C-W>k
nnoremap <S-Right> <C-W>l
tnoremap <S-Left> <C-\><C-N><C-W>h
tnoremap <S-Down> <C-\><C-N><C-W>j
tnoremap <S-Up> <C-\><C-N><C-W>k
tnoremap <S-Right> <C-\><C-N><C-W>l

nnoremap <Left> :bprev<CR>
nnoremap <Right> :bnext<CR>
nnoremap <Down> <C-D>
nnoremap <Up> <C-U>

" ' is more convenient than , and has redundancy with `
nnoremap ' ,

nnoremap Y y$

" needs map so that matchit works
map <Tab> %

nnoremap <silent> K :call kwp#KeywordPrg()<CR>

" }}}1 END MAPPINGS
" EDITING {{{1

set nrformats+=alpha

set whichwrap=h,l
set nojoinspaces

set shiftround

" incsearch doesn't set magic in substitutions
cnoremap s/ s/\v

set ignorecase
set smartcase
set gdefault

" }}}1 END EDITING
" DISPLAY {{{1

set cursorline
let $NVIM_TUI_ENABLE_CURSOR_SHAPE=1

set number
set relativenumber

set ruler
set rulerformat=%50(%{fugitive#statusline()}\ %t%=\ %P:\ %4l:\ %3c%)
set showcmd

set textwidth=80
set nowrap
" TODO: reexamine these settings
set tabstop=4  " number of columns <Tab> counts as visually
set shiftwidth=4  " columns added/removed when changing indent level
set softtabstop=4  " amount of whitespace corresponding to tab presses
set expandtab

" }}}1 END DISPLAY
" PLUGIN-SETTINGS {{{1
" BUFTABLINE {{{2

let g:buftabline_show = 1
let g:buftabline_indicators = 1
let g:buftabline_seperators = 1

highlight link BufTabLineCurrent StatusLine
highlight link BufTablineActive StatusLineNC
highlight link BufTablineHidden Normal
highlight link BufTablineFill Normal

" }}}2 END BUFTABLINE
" FUGITIVE {{{2

nnoremap <leader>g :Gstatus<CR>

" }}}2 END FUGITIVE
" RUST.VIM {{{2

let g:rust_fold = 1
let g:rust_bang_comment_leader = 1

" }}}2 END RUST
" PYTHON-MODE {{{2

let g:pymode_python = 'python3'
let g:pymode_lint_checkers = ['pyflakes', 'pylint', 'pep8', 'pep257', 'mccabe']
let g:pymode_syntax_print_as_function = 1

let g:pymode_options_colorcolumn = 0
let g:pymode_doc = 0
let g:pymode_run = 0
let g:pymode_rope = 0

" }}}2 END PYTHON-MODE
" INCSEARCH.VIM {{{2

map / <Plug>(incsearch-forward)
map ? <Plug>(incsearch-backward)
map g/ <Plug>(incsearch-stay)

let g:incsearch#auto_nohlsearch = 1
map n <Plug>(incsearch-nohl-n)
map N <Plug>(incsearch-nohl-N)
map * <Plug>(incsearch-nohl-*)
map # <Plug>(incsearch-nohl-#)
map g* <Plug>(incsearch-nohl-g*)
map g# <Plug>(incsearch-nohl-g#)

let g:incsearch#consistent_n_direction = 1

let g:incsearch#magic = '\v'

" }}}2 END INCSEARCH
" COLORSCHEMES {{{2

colorscheme solarized
set background=dark

" }}}2 END COLORSCHEMES
" }}}1 END PLUGIN-SETTINGS

" vim: foldmethod=marker foldlevel=0
