#!/usr/bin/env bash

error() {
    source "$HOME/.config/sh/utils/error"
}

exists() {
    source "$HOME/.config/sh/utils/exists"
}

if exists caffeinate
then
  caffeinate -dim
else
  error 'requires caffeinate, look into xdotool'
fi
