#!/usr/bin/env bash

exists() {
    source "$HOME/.config/sh/utils/exists"
}

"$@"

stat="$?"

msg="notify: $1"

if [[ "$stat" -eq 0 ]]
then
    msg="$msg succeeded"
else
    msg="$msg failed"
fi

if exists say
then
    say --voice='Fiona' "$msg"
else
    echo -e "$msg\a"
fi
